# Generated by Django 4.2.13 on 2024-11-14 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0014_remove_reviews_name_reviews_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsightProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carbon_footprint', models.FloatField(help_text='kg CO2e per unit')),
                ('water_footprint', models.FloatField(help_text='liters per unit')),
                ('energy_consumption', models.FloatField(help_text='kWh per unit')),
                ('chemical_emissions', models.FloatField(help_text='kg of toxic emissions per unit')),
                ('waste_recycling_rate', models.FloatField(help_text='kg waste recycled per unit')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('date_sold', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.insightproduct')),
            ],
        ),
    ]
