# Generated by Django 4.2.13 on 2024-11-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0015_insightproduct_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date_sold',
            field=models.DateTimeField(),
        ),
    ]
