# Generated by Django 4.2.13 on 2024-11-14 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0016_alter_sale_date_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insightproduct',
            name='carbon_footprint',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='insightproduct',
            name='chemical_emissions',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='insightproduct',
            name='energy_consumption',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='insightproduct',
            name='waste_recycling_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='insightproduct',
            name='water_footprint',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='Shop.product'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
